# Generated by Django 4.1.2 on 2022-12-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebbillapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebbill',
            old_name='state',
            new_name='districts',
        ),
    ]
