# Generated by Django 5.1.4 on 2025-02-26 05:18

import ebbillapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbillapp', '0002_rename_state_ebbill_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCarRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_brand', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_type', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('usage_of_car', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('price_start', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_end', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(db_comment='1 - request, 2 - callback, 3 - success,4 - unsuccess', default=1)),
                ('created_at', models.TextField(default=ebbillapp.models.get_local_time)),
                ('updated_at', models.TextField(default=ebbillapp.models.get_local_time)),
            ],
            options={
                'db_table': 'customer_car_request',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ebBill',
        ),
    ]
